import type { CSSProperties } from "react";

export type ThemeName = "green" | "red" | "blue" | "gray";

export const DEFAULT_THEME: ThemeName = "gray";
export const THEME_STORAGE_KEY = "__content_insights_ui_theme_v1__";

type ThemePalette = Record<string, string>;

type ThemeDefinition = {
  label: string;
  colors: ThemePalette;
};

const greenTheme: ThemePalette = {
  "ci-app-bg": "#0b221d",
  "ci-text-main": "#d8ebe5",
  "ci-text-primary": "#e7f2ee",
  "ci-text-strong": "#ffffff",
  "ci-text-muted": "#9cbeb3",
  "ci-text-subtle": "#8aa7a0",
  "ci-text-subtle-2": "#88aca1",
  "ci-text-subtle-3": "#88aba1",
  "ci-text-soft": "#bfd4cd",
  "ci-text-soft-2": "#b4d0c7",
  "ci-text-soft-strong": "#9cc2b7",
  "ci-text-heading-soft": "#d6e8e2",
  "ci-surface": "#0f1418",
  "ci-surface-raised": "#111a1f",
  "ci-surface-hover": "#141c21",
  "ci-surface-deep": "#0d2621",
  "ci-surface-accent-soft": "#16332c",
  "ci-surface-sidebar-card": "#163e35",
  "ci-surface-sidebar-card-hover": "#1b4d40",
  "ci-border": "#2e4f47",
  "ci-divider": "#ffffff33",
  "ci-control-border": "#2f6559",
  "ci-control-border-alt": "#3c665c",
  "ci-control-border-soft": "#3b8d76",
  "ci-control-border-strong": "#3d7e6a",
  "ci-control-border-icon": "#3b5f56",
  "ci-control-hover": "#10312a",
  "ci-control-hover-2": "#102b26",
  "ci-toggle-bg": "#131c21",
  "ci-toggle-active-bg": "#1b2b31",
  "ci-dropzone-active": "#102822",
  "ci-dropzone-hover": "#0f201d",
  "ci-upload-icon-bg": "#10332b",
  "ci-upload-icon-color": "#8cc5ae",
  "ci-chip-bg": "#16342d",
  "ci-chip-border": "#3f6f62",
  "ci-chip-text": "#b9d7cc",
  "ci-input-text": "#e4f0ec",
  "ci-input-field-text": "#e6f1ed",
  "ci-input-placeholder": "#6f8f85",
  "ci-input-label": "#6b8680",
  "ci-accent": "#4CB572",
  "ci-accent-soft": "#84baa6",
  "ci-accent-soft-strong": "#9fe5c5",
  "ci-accent-hover": "#3ea464",
  "ci-accent-button": "#1d6a54",
  "ci-accent-button-hover": "#257b61",
  "ci-accent-strong": "#2f7c5f",
  "ci-accent-strong-hover": "#3a916e",
  "ci-accent-strong-text": "#d5eee2",
  "ci-contrast-on-accent": "#13382f",
  "ci-tab-bg": "#2b735d",
  "ci-tab-hover": "#37876d",
  "ci-tab-border": "#4c8d78",
  "ci-tab-text": "#dcf3ea",
  "ci-tab-hover-text": "#bfd6ce",
  "ci-history-active-bg": "#1b5d4b",
  "ci-history-hover-bg": "#123c32",
  "ci-heading-title": "#f0f8f5",
  "ci-required": "#bf6a58",
  "ci-warning": "#d29d2d",
  "ci-error": "#b53d3d",
  "ci-error-soft": "#f0a7a7",
  "ci-error-text": "#ffd3d3",
  "ci-score-neutral": "#8aa39e",
  "ci-score-mid": "#E59F2E",
  "ci-score-bad": "#CB4E4E",
  "ci-ring-track": "#244139",
  "ci-icon-muted": "#79948d",
  "ci-icon-muted-2": "#7e9b93",
  "ci-icon-secondary": "#9cb6af",
  "ci-loading-text": "#9fd7c0",
  "ci-modal-bg": "#12241f",
  "ci-modal-border": "#2f584d",
  "ci-modal-text": "#eaf3f0",
  "ci-modal-subtext": "#a9c2ba",
  "ci-modal-icon": "#bfd4cd",
  "ci-modal-hover": "#17312a",
  "ci-modal-input-bg": "#1a2f29",
  "ci-modal-input-border": "#365e54",
  "ci-modal-input-placeholder": "#86a39c",
  "ci-modal-secondary-text": "#ccddd9",
  "ci-notice-bg": "#16362d",
  "ci-notice-border": "#3a8f77",
  "ci-notice-text": "#9dd5bf",
};

const redTheme: ThemePalette = {
  ...greenTheme,
  "ci-app-bg": "#241312",
  "ci-surface": "#171112",
  "ci-surface-raised": "#211617",
  "ci-surface-hover": "#28191a",
  "ci-surface-deep": "#2d1716",
  "ci-surface-accent-soft": "#3a2321",
  "ci-surface-sidebar-card": "#3f2423",
  "ci-surface-sidebar-card-hover": "#522d2c",
  "ci-border": "#5b3b39",
  "ci-control-border": "#774b49",
  "ci-control-border-alt": "#855453",
  "ci-control-border-soft": "#9a6462",
  "ci-control-border-strong": "#8c5b59",
  "ci-control-border-icon": "#734847",
  "ci-control-hover": "#3d2423",
  "ci-control-hover-2": "#351f1e",
  "ci-dropzone-active": "#2b1817",
  "ci-dropzone-hover": "#251514",
  "ci-upload-icon-bg": "#3d2422",
  "ci-upload-icon-color": "#e5a9a7",
  "ci-chip-bg": "#3b201f",
  "ci-chip-border": "#7b4b49",
  "ci-chip-text": "#efc8c7",
  "ci-input-placeholder": "#a28180",
  "ci-input-label": "#a98b8a",
  "ci-accent": "#dd7272",
  "ci-accent-soft": "#e9a8a8",
  "ci-accent-soft-strong": "#f0bebe",
  "ci-accent-hover": "#c86464",
  "ci-accent-button": "#8f4545",
  "ci-accent-button-hover": "#a95454",
  "ci-accent-strong": "#a35151",
  "ci-accent-strong-hover": "#bf6161",
  "ci-accent-strong-text": "#fff0f0",
  "ci-contrast-on-accent": "#2d1313",
  "ci-tab-bg": "#7e4040",
  "ci-tab-hover": "#985252",
  "ci-tab-border": "#b86d6d",
  "ci-tab-text": "#ffe8e8",
  "ci-tab-hover-text": "#ffd3d3",
  "ci-history-active-bg": "#6b3535",
  "ci-history-hover-bg": "#4a2626",
  "ci-heading-title": "#ffecec",
  "ci-required": "#f1917e",
  "ci-warning": "#e9b252",
  "ci-ring-track": "#4d2d2c",
  "ci-text-main": "#f0dedc",
  "ci-text-primary": "#fff1ef",
  "ci-text-muted": "#d6b7b6",
  "ci-text-subtle": "#bf9a99",
  "ci-text-subtle-2": "#c79f9d",
  "ci-text-subtle-3": "#be9695",
  "ci-text-soft": "#e9c9c7",
  "ci-text-soft-2": "#ddb5b3",
  "ci-text-soft-strong": "#d8aaa8",
  "ci-text-heading-soft": "#f5dedd",
  "ci-icon-muted": "#ba9594",
  "ci-icon-muted-2": "#c6a1a0",
  "ci-icon-secondary": "#c8a4a3",
  "ci-loading-text": "#efb8b7",
};

const blueTheme: ThemePalette = {
  ...greenTheme,
  "ci-app-bg": "#0f1c2b",
  "ci-surface": "#101620",
  "ci-surface-raised": "#151e2b",
  "ci-surface-hover": "#1a2432",
  "ci-surface-deep": "#12263a",
  "ci-surface-accent-soft": "#173048",
  "ci-surface-sidebar-card": "#17364f",
  "ci-surface-sidebar-card-hover": "#1e4565",
  "ci-border": "#35516f",
  "ci-control-border": "#406081",
  "ci-control-border-alt": "#486b8f",
  "ci-control-border-soft": "#5387b7",
  "ci-control-border-strong": "#4f79a3",
  "ci-control-border-icon": "#426789",
  "ci-control-hover": "#17324c",
  "ci-control-hover-2": "#173149",
  "ci-dropzone-active": "#122436",
  "ci-dropzone-hover": "#112133",
  "ci-upload-icon-bg": "#173550",
  "ci-upload-icon-color": "#9ac7f1",
  "ci-chip-bg": "#193449",
  "ci-chip-border": "#3f6f99",
  "ci-chip-text": "#b8d8f4",
  "ci-input-placeholder": "#7d97b3",
  "ci-input-label": "#8ea7c1",
  "ci-accent": "#5aa7ff",
  "ci-accent-soft": "#8ec4ff",
  "ci-accent-soft-strong": "#a8d3ff",
  "ci-accent-hover": "#4797f2",
  "ci-accent-button": "#2c6db8",
  "ci-accent-button-hover": "#3a7bc7",
  "ci-accent-strong": "#2f79ca",
  "ci-accent-strong-hover": "#3d8be0",
  "ci-accent-strong-text": "#e7f2ff",
  "ci-contrast-on-accent": "#0f2c49",
  "ci-tab-bg": "#356ea8",
  "ci-tab-hover": "#4581be",
  "ci-tab-border": "#5d97cf",
  "ci-tab-text": "#e0efff",
  "ci-tab-hover-text": "#c9e2ff",
  "ci-history-active-bg": "#2b5d90",
  "ci-history-hover-bg": "#20466c",
  "ci-heading-title": "#eaf3ff",
  "ci-required": "#e58f6d",
  "ci-warning": "#f0bd5a",
  "ci-ring-track": "#274566",
  "ci-text-main": "#dce8f6",
  "ci-text-primary": "#eaf3ff",
  "ci-text-muted": "#adc1d7",
  "ci-text-subtle": "#93abca",
  "ci-text-subtle-2": "#9eb4d1",
  "ci-text-subtle-3": "#97afce",
  "ci-text-soft": "#c5d8ec",
  "ci-text-soft-2": "#b3c8df",
  "ci-text-soft-strong": "#a6bdd7",
  "ci-text-heading-soft": "#d5e7fb",
  "ci-icon-muted": "#8ea9c8",
  "ci-icon-muted-2": "#9ab2cf",
  "ci-icon-secondary": "#9eb5d3",
  "ci-loading-text": "#a5c8ef",
};

const grayTheme: ThemePalette = {
  ...greenTheme,
  "ci-app-bg": "#181a1f",
  "ci-surface": "#1e2127",
  "ci-surface-raised": "#242932",
  "ci-surface-hover": "#2a2f39",
  "ci-surface-deep": "#212630",
  "ci-surface-accent-soft": "#2d333e",
  "ci-surface-sidebar-card": "#303743",
  "ci-surface-sidebar-card-hover": "#394252",
  "ci-border": "#4a5566",
  "ci-control-border": "#566175",
  "ci-control-border-alt": "#5f6b82",
  "ci-control-border-soft": "#6a7891",
  "ci-control-border-strong": "#66738d",
  "ci-control-border-icon": "#58657d",
  "ci-control-hover": "#313846",
  "ci-control-hover-2": "#2c3442",
  "ci-dropzone-active": "#262d39",
  "ci-dropzone-hover": "#222936",
  "ci-upload-icon-bg": "#313947",
  "ci-upload-icon-color": "#b7c2d1",
  "ci-chip-bg": "#303947",
  "ci-chip-border": "#5f6f87",
  "ci-chip-text": "#cfd8e5",
  "ci-input-placeholder": "#98a3b4",
  "ci-input-label": "#a8b2c1",
  "ci-accent": "#8ea1ba",
  "ci-accent-soft": "#a9b8ca",
  "ci-accent-soft-strong": "#bdc8d7",
  "ci-accent-hover": "#7f93ad",
  "ci-accent-button": "#5f738e",
  "ci-accent-button-hover": "#70839c",
  "ci-accent-strong": "#667e99",
  "ci-accent-strong-hover": "#7990aa",
  "ci-accent-strong-text": "#edf2f7",
  "ci-contrast-on-accent": "#1e2733",
  "ci-tab-bg": "#5f7490",
  "ci-tab-hover": "#70839e",
  "ci-tab-border": "#7f92ac",
  "ci-tab-text": "#ecf1f7",
  "ci-tab-hover-text": "#d9e1ec",
  "ci-history-active-bg": "#546780",
  "ci-history-hover-bg": "#3e4d61",
  "ci-heading-title": "#edf2f7",
  "ci-required": "#d88c73",
  "ci-warning": "#d3ab5a",
  "ci-ring-track": "#3f4b5d",
  "ci-text-main": "#dde4ee",
  "ci-text-primary": "#edf2f7",
  "ci-text-muted": "#b2bdcc",
  "ci-text-subtle": "#9ea9b9",
  "ci-text-subtle-2": "#a9b4c4",
  "ci-text-subtle-3": "#a1acbc",
  "ci-text-soft": "#c8d1de",
  "ci-text-soft-2": "#bbc6d6",
  "ci-text-soft-strong": "#afbccf",
  "ci-text-heading-soft": "#d7e0eb",
  "ci-icon-muted": "#9cabbf",
  "ci-icon-muted-2": "#a7b5c8",
  "ci-icon-secondary": "#acb9cc",
  "ci-loading-text": "#b5c3d6",
};

export const THEME_CONFIG: Record<ThemeName, ThemeDefinition> = {
  green: { label: "Green", colors: greenTheme },
  red: { label: "Red", colors: redTheme },
  blue: { label: "Blue", colors: blueTheme },
  gray: { label: "Gray", colors: grayTheme },
};

export function isThemeName(value: unknown): value is ThemeName {
  return (
    typeof value === "string" &&
    Object.prototype.hasOwnProperty.call(THEME_CONFIG, value)
  );
}

export function getThemeCssVars(theme: ThemeName): CSSProperties {
  const palette = THEME_CONFIG[theme].colors;
  const style: Record<string, string> = {};

  for (const [token, color] of Object.entries(palette)) {
    style[`--${token}`] = color;
  }

  return style as CSSProperties;
}

